language: java
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk9

notifications:
  slack:
    secure: Oj4R5k9wuVTrXAVnY9nc8JZ16U/Rs/4U7Zb+n0Z/mjfsrBf6KE+W/tEyztZhwYgU/Cs2WILosZgU8jlIvMYosIJuJXA2ORuxqcqLR7yPHofTKd/0xQakkzHAXtUOkCextZTVsKiG2XL9BitQnxZwPDpNwCEgHaWJ70v8mPpBxP4=
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/247b3c6e28a2d6b498fe
