site_name: Orbit
theme: readthedocs
nav:
  - About: index.md
  - Getting Started:
      - Dependencies: getting-started/dependencies.md
  - User Guide:
      - Logging: user-guide/logging.md
  - Developer Guide:
      - Building: developer-guide/building.md